//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.DataModel
{
    using System;
    using System.Collections.Generic;
    //using Core.Utility;

    //[DBTable("Menu", TableDesc = "Menu")]
    public partial class Menu
    {
        //[DBField("Id")]
        public int Id { get; set; }
        //[DBField("MenuNumber")]
        public int MenuNumber { get; set; }
        //[DBField("ParentNumber")]
        public Nullable<int> ParentNumber { get; set; }
        //[DBField("MenuName")]
        public string MenuName { get; set; }
        //[DBField("Uri")]
        public string Uri { get; set; }
        //[DBField("Icon")]
        public string Icon { get; set; }
    }
}
